apiVersion: v1
kind: Service
metadata:
  name: metrics-app
  namespace: monitoring-demo
spec:
  selector:
    app: metrics-app
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP